### ISSUE TITLE
Mention actual GitHub URL

### ISSUE THREAD

**Issue by jidanni** [mrdvt92/perl-Geo-Inverse#1]
Due to https://github.com/metacpan/metacpan-web/issues/2872 it might be best to mention the actual GitHub link within in the package.

**Comment by mrdvt92** [comment]
The URL is set in the Makefile.PL file for the generation of the JSON/YAML files.  All three files appear to be correctly formatted in regard to resources pointing to GitHub.  Please explain why this is not enough for your application.

```
resources:
  bugtracker: https://github.com/mrdvt92/perl-Geo-Inverse/issues
  homepage: https://github.com/mrdvt92/perl-Geo-Inverse
  repository: https://github.com/mrdvt92/perl-Geo-Inverse.git
```

```
  'META_MERGE'  => {
                    'resources' => {
                      'repository' => {
                        'web' => 'https://github.com/mrdvt92/perl-Geo-Inverse.git',
                        'url' => 'git@github.com:mrdvt92/perl-Geo-Inverse.git',
                        'type' => 'git'
                      },
                      'homepage' => 'https://github.com/mrdvt92/perl-Geo-Inverse',
                      'bugtracker' => {
                        'web' => 'https://github.com/mrdvt92/perl-Geo-Inverse/issues'
                      }
```
